ClickHouse/terraform-provider-clickhouse

clickhouse/provider.go
The code as written reads a default value for tokenSecret by reading the 'CLICKHOUSE_TOKEN_KEY' environment variable, same as the token key; I think this is a typo and this commit reads the secret from a separate environment variable.
=> Read token secret from CLICKHOUSE_TOKEN_SECRET environment variable

clickhouse/service.go, examples/basic/main.tf
there's a bug in the current version where if the user edits the ip access list in certain ways it'll give an `unexpected new value` error because of how we interact with ClickHouse OpenAPI for updating the list with the `add` and `remove` keys.
this pr changes the behavior to simply remove all old items and add the new items in the order specified in terraform so that the order is correctly returned by the api
=> remove all old ip access items and add all new items to preserve order

clickhouse/client.go, clickhouse/service.go, examples/basic/main.tf
the provider previously ignored the double sha1 password hash when updating the instance's password, which meant users that connected to their instances using the mysql protocol weren't able to connect with the expected password
=> add support for mysql protocol users with either the `password` key or a new `double_sha1_password_hash` key

README.md
I had to use `"clickhouse/clickhouse"` in my `.terraformrc` for `terraform plan` to work. Otherwise, it complained that I didn't run init.
=> Update readme for development instructions

clickhouse/provider.go
This documents the `CLICKHOUSE_` environment variables that can be used for the provider config. Had to dig into the code to find these as is.
=> chore(docs): update provider docs for environment variable options

clickhouse/provider.go
Per the docs and the code it looks like the provider is able to load credentials via environment variables. But because the schema sets those fields to required and requires a valid string, this doesn't actually work.
Simple fix, make those fields optional in the schema. Validation still works as intended.
=> fix: allow setting provider credentials via env

clickhouse/client.go, clickhouse/service.go, docs/resources/service.md
Add `num_replicas` field to control the number of replicas (field `numReplicas` in `/scaling`: https://clickhouse.com/docs/en/cloud/manage/api/swagger#/paths/~1v1~1organizations~1:organizationId~1services~1:serviceId~1scaling/patch).
=> Allow adjusting the number of replicas for existing services

clickhouse/service.go
Step to reproduce (before the fix)
- in .tf file, configure ipAccessList with 1 item
- apply the TF change.
- in the UI you should see this IP. 
- Now add a new ip in the UI, and **set the description to empty.**
- reapply TF
Expected behavior
- Terraform provider should not crash
Actual behavior
- Terraform provider crashes
closes https://github.com/ClickHouse/support-escalation/issues/2259
closes https://github.com/ClickHouse/control-plane/issues/9213
=> Fix ipAccessList index out of range

.gitignore, clickhouse/clickhouse_service_private_endpoint_attachment.go, clickhouse/client.go, clickhouse/datasource.go, clickhouse/private_endpoint_registration.go, clickhouse/provider.go, examples/PrivateLink/aws.tf, examples/PrivateLink/main.tf
This PR solves this [issue](https://github.com/ClickHouse/terraform-provider-clickhouse/issues/30). To solve the issue we need to have a ClickHouse service provisioned first before attaching the endpoints because the endpoints creation depends on the ClickHouse service itself. I moved endpoint attachment to a new resource so it happens after the endpoints are created.
=> Issues supporting aws privatelink

README.md, clickhouse/provider.go
Looks like 'environment' key is not supported anymore. Cleaned up the code and updated doc.
=> fix obsolete instructions on how to use different environment

.gitignore, clickhouse/service.go, docs/resources/service.md
Fixes #47 
1) idle_scaling param should not affect min_total_memory_gb and max_total_memory_gb
2) idle_scaling and idle_timeout_minutes should be configurable for dev tier too
There is some duplication for checks in Create and Update. It can be addressed in separate PR with addition of more test-cases.
=> Update handling for idle parameters

clickhouse/service.go
Encryption fields were never set in the state, setting them on refresh
=> Always set encryption fields in status

clickhouse/service.go
It is possible to change idle settings (enabled/disabled and timeout) for dev tier as well, but terraform provider state doesn't reflect this.
=> Update idleScaling and idleTimeoutMinutes for dev tier as well

pkg/resource/service.go
Doing this leads to an apply time error, so blocking it
=> Prevent setting idle_timeout_minutes if idle_scaling is false

.github/actions/e2e/action.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml
Run end to end tests every night.
Helps to find regressions with new releases of terraform cli or with changes in the control plane API
=> Add a nightly run for e2e tests

.github/workflows/e2e.yaml, Makefile, docs/resources/service.md, pkg/internal/api/errors.go, pkg/resource/models/service_resource.go, pkg/resource/models/service_resource_test.go, pkg/resource/private_endpoint_registration.go, pkg/resource/service.go, pkg/resource/service_test.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/137
Deprecate and avoid using `private_endpoint_ids` attribute for the `service` resource.
The feature will be replaced by a standalone resource in a followup PR.
Of course this is a breaking change and will be released in a major version.
=> Remove private endpoints from service

docs/resources/private_endpoint_registration.md, examples/full/private_endpoint/aws/main.tf, examples/resources/clickhouse_private_endpoint_registration/resource.tf, pkg/resource/models/private_endpoint_registration.go, pkg/resource/private_endpoint_registration.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/135
Renaming the `id` field in `private_endpoint_registration` to a more appropiare `private_endpoint_id`
as a side effect, we make the provider more "pulumi friendly" as per customer request.
=> rename "id" to "private_endpoint_id" in "private_endpoint_registration"

README.md, docs/index.md, docs/resources/service.md, pkg/provider/README.md, pkg/provider/provider.go, pkg/resource/models/service_resource.go, pkg/resource/private_endpoint_registration.go, pkg/resource/service.go, pkg/resource/service_private_endpoints_attachment.go
In the upcoming 1.0.0 release we were forced to introduce a few breaking changes  to our provider, by some otherwise unsolvable problems.
Unfortunately, these changes (we split a resource in 2 resources) are not automatically handlable via code, and manual steps are required.
This PR adds the needed steps during such upgrade to the github readme and references it in the docs that go in the terraform website.
=> Breaking change documentation and handling

.github/workflows/e2e.yaml, go.mod, go.sum, pkg/internal/api/client.go, pkg/internal/api/client_mock.go, pkg/internal/api/constants.go, pkg/internal/api/errors.go, pkg/internal/api/interface.go, pkg/resource/service.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/133
This PR:
- Replaces own code with backoff library for backoff type use cases
- Add automatic retry of 429 and 5xx errors
as a side effect this PR makes end to end tests dramatically more reliable
=> Improve retry logic

.air.toml, .github/workflows/release.yaml, .goreleaser.yml, pkg/internal/api/client.go, pkg/project/project.go
For tracking purposes, we want to add a user-agent header to all http requests to the API.
This way we can server side have an idea on how many users are using the terraform provider and which version
=> Add user agent

.goreleaser.yml
the missing version label made the config file being ignored during releases
=> Fix goreleaser config file

go.mod, pkg/datasource/datasource.go, pkg/internal/api/client.go, pkg/internal/api/client_mock.go, pkg/internal/api/constants.go, pkg/internal/api/errors.go, pkg/internal/api/interface.go, pkg/resource/private_endpoint_registration.go, pkg/resource/service.go, pkg/resource/service_private_endpoints_attachment.go, pkg/resource/service_test.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/148
We want to be more gentle on the backend API, thus we try to honour the response header indicating how long to wait before making another call.
Also fixed debug logging
=> Honor server-side throttling info while dealing with 429 errors

.github/workflows/e2e.yaml, README.md, development/README.md, docs/resources/service.md, examples/full/basic/aws/main.tf, examples/full/basic/azure/main.tf, examples/full/basic/gcp/main.tf, examples/full/private_endpoint/aws/main.tf, pkg/internal/api/client.go, pkg/internal/api/client_mock.go, pkg/internal/api/interface.go, pkg/internal/api/models.go, pkg/resource/models/service_resource.go, pkg/resource/service.go, pkg/resource/service_test.go
Towards: https://github.com/ClickHouse/sre/issues/89 and https://github.com/ClickHouse/support-escalation/issues/2656
Add 2 new fields `max_replica_memory_gb` and `min_replica_memory_gb` to allow specifying replica size and avoid confusion when the number of replicas is not 3.
The old fields (`max_total_memory_gb` and `min_total_memory_gb`) are kept as deprecated for now and will be remove in a future release.
The buggy behaviour will be kept by always dividing the deprecated fields' value by 3, regardless of the acutal number of replicas in the service.
=> Fix wrong calculation of memory size while caling services with more than 3 replicas

examples/full/private_endpoint/aws/aws.tf
Towards: https://github.com/ClickHouse/sre/issues/98
Instead of hardcoding "a" and "b" that are not available on all regions
=> use data source to pick availability zones for AWS

pkg/resource/private_endpoint_registration.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/166
this is a bug from a previous PR when we renamed one attribute from "id" to "private_endpoint_id".
Unfortunately, I forgot to rename one occourence of the attribute.
=> Fix import of private_endpoint_registration resource

.github/workflows/release.yaml, docs/index.md, examples/provider/provider.tf.template, pkg/resource/service.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/173
The `idle_scaling` field was marked as optional, but it's defaulted on the server side and it was not marked as computed, making `terraform apply` to fail.
=> Make idle_scaling field computed

.github/workflows/e2e.yaml, .github/workflows/release.yaml
Currently if a test run fails, the whole pipeline is correctly marked as failed as well.
Problem: if we try to "rerun failed jobs" only, even if they pass, the pipeline still is marked as failed.
This PR is an attempt to make the pipleine marked as successful after a successful "rerun failed jobs"
=> Improve retriability of e2e tests

.github/workflows/autolabel.yaml
We need this to distribute the issues in the team board
=> Automatically label issue with 'terraform-provider'

docs/index.md, docs/resources/service_private_endpoints_attachment.md, examples/full/private_endpoint/aws/README.md, main.go, pkg/provider/README.md, pkg/resource/service_private_endpoints_attachment.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/190
fix a bug that prevented multiple private endpoints to be attached to the same service
=> Fix attachment of multiple private endpoints to the same service

.github/scripts/set_api_env.sh
When the e2e env setting script is called by the cron schedule inputs are empty so we default to Production.
=> default to production for e2e tests

pkg/internal/api/errors.go, pkg/internal/api/service.go
In case of a 500 (server side error) we don't want to keep retrying too long as there is not much we can do to solve it on the client side.
before this PR there were 2 nested retry loops in case of server side 500 that kept the user waiting uselessly for several minutes.
with this change, in the "external" retry loop we check and return early in case of 500
=> Fast fail in case of 500

examples/clickpipe/kafka_azure_eventhub/provider.tf, examples/clickpipe/kafka_confluent/provider.tf, examples/clickpipe/kafka_msk_iam_user/provider.tf, examples/clickpipe/kafka_offset_strategy/provider.tf, examples/clickpipe/kafka_redpanda_scram/provider.tf, examples/clickpipe/kafka_schema_registry/provider.tf, examples/clickpipe/multiple_pipes_example/README.md, examples/clickpipe/multiple_pipes_example/main.tf, examples/clickpipe/multiple_pipes_example/provider.tf, examples/clickpipe/multiple_pipes_example/variables.sample.tfvars, examples/clickpipe/object_storage_iam_role/provider.tf, examples/clickpipe/object_storage_iam_user/provider.tf, examples/clickpipe/service_and_clickpipe/provider.tf, pkg/internal/api/clickpipe.go, pkg/internal/api/clickpipe_models.go, pkg/resource/clickpipe.go
- remove import implementation as it's broken now
- Omit empty timestamp in Kafka offset strategy
- Wait desired plan state is reached after scaling ClickPipe
- Restore variables in ClickPipes provider examples
- Add a UseStateForUnknown modifier for Kafka consumer group attribute
- Allow empty description
- Handle ClickPipe state changes more gracefully
- multiple_pipes_example
=> Experimental ClickPipe resource fixes

.github/workflows/release.yaml, Makefile, examples/users/basic/README.md, examples/users/basic/main.tf, examples/users/basic/provider.tf, examples/users/basic/provider.tf.template.alpha, examples/users/basic/variables.tfvars.sample, pkg/internal/api/client_mock.go, pkg/internal/api/db_user.go, pkg/internal/api/interface.go, pkg/resource/descriptions/user.md, pkg/resource/models/user.go, pkg/resource/register_debug.go, pkg/resource/user.go
Towards: https://github.com/ClickHouse/sre/issues/307
this PR adds a new alpha resource to allow creating a user in a clickhouse service.
This is on purpose a partial PR: it is possible to create and update and delete users, but there are no roles assigned so users created by this resource are currently useless.
Managing and assignment of roles will come in a future PR
=> add user resource

.github/workflows/release.yaml
it caused https://github.com/ClickHouse/terraform-provider-clickhouse/actions/runs/13240046246 to fail
=> Fix bump job in release

.goreleaser-alpha.yml
Marking alpha releases as "pre release" prevent them from being picked up by hashicorp in the public terraform provider page.
We still don't mark the alpha releases as "latest" so it shouldn't change much on github side.
=> Avoid marking alpha releases as "pre releases"

examples/rbac/main.tf, pkg/resource/grant_privilege.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/250
Allow lowercase privileges in `clickhouse_grant_privilege`.
This makes UX slightly worse, because a client will be allowed to set "select" as a privilege, but it will be rejected by the server with an error like this:
```
│ Could not create privilege grant, unexpected error: status: 400, body: {"error":{"code":"691","details":"Unknown element 'select' for enum, maybe you meant: ['SELECT']: while converting 'select' to Enum16('SHOW DATABASES' = 0, 'SHOW TABLES' = 1, 'SHOW COLUMNS' = 2, 'SHOW DICTIONARIES' = 3, 'SHOW' =
│ 4, 'SHOW FILESYSTEM CACHES' = 5, 'SELECT' = 6, 'INSERT' = 7, 'ALTER UPDATE' = 8, 'ALTER DELETE' = 9, 'ALTER ADD COLUMN' = 10, 'ALTER MODIFY COLUMN' = 11, 'ALTER DROP COLUMN' = 12, 'ALTER …
```
=> allow lowercase letters in grant_privilege

docs/resources/service.md, pkg/resource/service.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/252
Mark `ip_access/description` field as required.
Given the bug, there can't be any customer who set it to null.
There might be some who set it to `""`, but that should work.
The description field obviously doesn't serve any practical purpose, so marking as required is both the easiest and the safest choice in this case.
=> Mark ip_access/description field as required

examples/full/basic/azure/main.tf, examples/full/basic/gcp/main.tf, pkg/internal/api/backup_configuration.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/255
There was a quirk in the API client that made it impossible to set the backup_period_in_hours field
=> Fix error when setting backup_configuration.backup_period_in_hours

pkg/internal/api/common.go
To mitigate the 400 errors we occasionally get from the API, I would like to improve the retry mechanism on the client side.
Now we only retry calls if they end up in a 5xx status code, we should retry also for 400 (not 4xx) responses as well.
=> add  400 status code handling in retry logic

pkg/internal/api/common.go, pkg/resource/service.go
In case of a server side error leading to a 500, the client side retry logic sent an invalid request (without the body) leading to an error from cloudfront.
This PR fixes the retry logic error.
=> Fix wrong retry logic

pkg/resource/service.go
"Optional, Computed" fields are confusing for customers, as they show up as being changed every time there is an unrelated change in the .tf file.
This PR removes the Computed flag from 2 attributes where it was not really needed
=> Avoid change fields

docs/resources/service.md, pkg/resource/service.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/267
Changed some field's config to avoid having too many changes in the plan when unrelated attributes are changed.
=> Improve fields

.github/workflows/e2e.yaml, docs/index.md, pkg/internal/api/client.go, pkg/internal/api/client_test.go, pkg/internal/api/common.go, pkg/internal/api/service.go, pkg/provider/provider.go
In case of client timeout we didn't log the requests.
This PR fixes that and adds possibility to change the default HTTP timeout for the API client
=> improve loggin in case of errors. make client timeout configurable

docs/resources/service.md, pkg/resource/service.go
Towards: https://github.com/ClickHouse/sre/issues/382
smarter ModifyPlan to avoid marking the `mysql` endpoint as always dirty.
Related to support escalation https://github.com/ClickHouse/support-escalation/issues/4509
=> Mysql plan

examples/full/warehouse/aws/main.tf, pkg/resource/service.go
Enabling query api endpoints on hydra children is currently not possible.
this PR changes that
=> fix enabling query api endpoints on hydra children

pkg/resource/service.go
towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/295
in version 3.0.0 we introduced a schema change in clickhouse_service that required migration, and we did that automatically for our customers.
in 3.1.0 we added a new field to the same schema, but we didn't update the migration code to write the new field.
when customers upgrade a service from <3.0.0 to >= 3.1.0 (skipping 3.0.0) the new field is missing and terraform complains about that.
this PR fixed this mess
=> add tde field when upgrading schema in clickhouse_service

.github/actions/e2e/action.yaml, .github/workflows/e2e.yaml
Towards: https://github.com/ClickHouse/sre/issues/389
allow picking what version to test upgrade from during e2e tests on a PR
=> allow picking what version to test upgrade from

docs/resources/service.md, pkg/internal/api/models.go, pkg/internal/api/service.go, pkg/resource/models/service_resource.go, pkg/resource/service.go
Added support to restore from a backup when creating a new resource.
When calling
```
POST /v1/organizations/{organizationId}/services
```
to create a new service, allowed passing an optional field
```
"backupId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
```
Ensured:
=> add the capability to create new services from existing backups

pkg/resource/register_debug.go
We switched to the external provider for the same feature.
Proper cleanup will follow
=> Disable RBAC resources from the alpha build

pkg/resource/service.go
Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/335
validate `idle_timeout` equals to true if `idle_timeout_minutes` is set.
=> validate idle_timeout is enabled if `idle_timeout_minutes` is set

examples/clickpipe/object_storage_azure_blob/README.md, examples/clickpipe/object_storage_azure_blob/main.tf, examples/clickpipe/object_storage_azure_blob/provider.tf, examples/clickpipe/object_storage_azure_blob/provider.tf.template.alpha, examples/clickpipe/object_storage_azure_blob/variables.sample.tfvars, pkg/internal/api/clickpipe.go, pkg/internal/api/clickpipe_models.go, pkg/resource/clickpipe.go, pkg/resource/models/clickpipe_resource.go
This PR adds support for Azure Blob Storage as a source for ClickPipe data ingestion pipelines, enabling users to ingest data directly from Azure Blob containers.
- **New object storage type:** `azureblobstorage`
- **New authentication method:** `CONNECTION_STRING` for Azure
- **New configuration fields:**
- `connection_string` - Azure connection string (sensitive)
- `path` - File path within container with wildcard support
- `azure_container_name` - Azure container nam
Related to https://github.com/ClickHouse/clickpipes-platform/issues/4382
=> Add Azure Blob Storage support to ClickPipe object storage

examples/resources/clickhouse_clickpipes_reverse_private_endpoint/import.sh
I noticed that in your docs for [reverse private endpoints](https://registry.terraform.io/providers/ClickHouse/clickhouse/3.4.1-alpha1/docs/resources/clickpipes_reverse_private_endpoint#import), it says that you can import an existing resource with
```
terraform import clickhouse_clickpipes_reverse_private_endpoint.example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
But this doesn't actually work! You need to specify the ID of the reverse private endpoint, not the ClickPipe that it's used in. Note that the ID of a reverse private endpoint isn't actually accessible via the UI; I had to use the API to find the ID.
I'm not sure how to update your actual Terraform docs but this is a start.
=> fix example for importing reverse private endpoint

pkg/resource/clickpipe.go
This fixes an issue I missed where editing would require CPU & Memory & replicas when all fields should actually be optional. This was properly implemented in the creation workflow but was missed in the editing workflow.
=> Fix editing for scaling replicas to ensure all fields are optional as well

.github/workflows/comments.yaml
- Workflow fails since dependabot cannot access secrets
=> ci(comment): exclude dependabot

.github/actions/e2e/action.yaml
Don't override CI files during upgrade test at the middle of CI execution
To address issues like: https://github.com/ClickHouse/terraform-provider-clickhouse/actions/runs/17703162399/job/50321988800
=> fix: don't override CI files during upgrade test at the middle of CI execution

README.md
While looking at the private endpoint examples, I noticed some references to an `aws_red` service that doesn't seem to match the service name in other parts of the examples.
I'm assuming that this was a bad copy paste, so I made the examples consistent.
Note that I didn't check this and I'm assuming that's how the private service definition works (as I'm still learning about them). Please double check if the changes are correct 😅
=> Avoid confusing references to AWS red

.github/actions/e2e/action.yaml, .github/actions/import/action.yaml, examples/full/basic/azure/main.tf, examples/full/private_endpoint/azure/azure.tf, examples/full/private_endpoint/azure/main.tf
Some CI bug accumulated recently, address them all
Example of release run with all the bugs:
https://github.com/ClickHouse/terraform-provider-clickhouse/actions/runs/17771608352
Green E2E:
- staging: https://github.com/ClickHouse/terraform-provider-clickhouse/actions/runs/17782439416
=> fix: TF provider CI failures

.github/workflows/release.yaml, examples/full/private_endpoint/azure/azure.tf
Normalize service name to use in the names of the Azure resources be with requirements of Azure
https://github.com/ClickHouse/terraform-provider-clickhouse/actions/runs/17785231096/job/50551470950
```
Error: name must be between 1 - 80 characters long, begin with a letter or number, end with a letter, number or underscore, and may contain only letters, numbers, periods, hyphens or underscores
with azurerm_private_endpoint.this,
on azure.tf line 45, in resource "azurerm_private_endpoint" "this":
45:   name                = var.service_name
```
E2E: https://github.com/ClickHouse/terraform-provider-clickhouse/actions/runs/17787396035
=> fix: Pass proper service name in Release workflow

.github/actions/import/action.yaml, .github/workflows/e2e.yaml, .github/workflows/import.yaml, .github/workflows/release.yaml
As the number of end-to-end (E2E) tests increases, the stability of the CI pipeline is decreasing. Test failures often occur for reasons unrelated to Terraform, such as:
•	Random instance provisioning timeouts
•	Occasional failures of GitHub runners
•	Tests being executed across different regions in random rotation, leading to regional issues
•	etc.
Currently, a single failed test requires rerunning the entire workflow, which makes achieving a “green” pipeline very challenging - especially given the long runtime of each workflow execution, this hurts mostly release workflow
The fix is to add ability to rerun-tests + tuning around
Example of test pipeline: https://github.com/ClickHouse/terraform-provider-clickhouse/actions/runs/17819847509
=> fix: add ability to rerun failed tests
