clickhouse/service.go
examples/basic/main.tf

fix idle_scaling key not being set correctly for dev services

---

clickhouse/service.go

Fixes: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/12

Update nested IP access list

---

clickhouse/client.go
clickhouse/service.go
examples/basic/main.tf

add iam_role as a computed value on services

---

examples/privatelink/README.md
examples/privatelink/aws.tf
examples/privatelink/main.tf
examples/privatelink/variables.tfvars

AWS private link examples

---

clickhouse/client.go
clickhouse/service.go

closes https://github.com/ClickHouse/control-plane/issues/8524

don't get private endpoint config for azure instances

---

clickhouse/service.go

fixes inconsistent state for encryption_key, encryption_assumed_role_identifier, idle_scaling, min_total_memory_gb, max_total_memory_gb, and idle_timeout_minutes

fix inconsistent state for certain terraform keys as these are optional arguments

---

examples/PrivateLinkAzure/README.md
examples/PrivateLinkAzure/azure.tf
examples/PrivateLinkAzure/main.tf
examples/PrivateLinkAzure/variables.tfvars

Complete example that creates services and azure private link

Example for azure private link

---

examples/PrivateLinkAzure/README.md
examples/PrivateLinkAzure/azure.tf
examples/PrivateLinkAzure/main.tf

to workaround https://github.com/hashicorp/terraform-provider-azurerm/issues/17011

Updating azure Private Link example

---

clickhouse/client_test.go
clickhouse/datasource.go
go.mod

add first unit test

---

.github/workflows/stale.yml

Add workflow to nudge or close stale issues/PRs.

Add workflow to nudge or close stale issues/PRs

---

clickhouse/models.go
clickhouse/models_test.go
clickhouse/service.go
internal/test/updater.go

…add interface for mocking purposes
more Resource model to own file and implement Equals function to allow comparison between instances.
Implement unit test to check Equals function

base ground for testing

---

.golangci.yml
clickhouse/clickhouse_service_private_endpoint_attachment.go
clickhouse/datasource.go
clickhouse/models_test.go
clickhouse/private_endpoint_registration.go
clickhouse/provider.go
clickhouse/service.go
go.mod
main.go

Change module name and reformat code

Change module name

---

.github/workflows/make-release.yaml
.github/workflows/prepare-release.yaml
.github/workflows/release.yaml
examples/PrivateLink/main.tf
examples/PrivateLink/provider.tf
examples/PrivateLink/provider.tf.template
examples/PrivateLinkAzure/main.tf
examples/PrivateLinkAzure/provider.tf
examples/PrivateLinkAzure/provider.tf.template
examples/PrivateServiceConnect/main.tf
examples/PrivateServiceConnect/provider.tf
examples/PrivateServiceConnect/provider.tf.template
examples/basic/main.tf
examples/basic/provider.tf
examples/basic/provider.tf.template

Added 2 github actions to simplify the workflow process and automate parts of it

Release automation

---

pkg/internal/tfutils/utils.go
pkg/resource/service.go

Trying to solve this error: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/115

Use Terraform functions to compare List attributes

---

.github/actions/e2e/action.yaml
.github/workflows/e2e.yaml
.github/workflows/release.yaml
examples/full/basic/aws/main.tf
examples/full/basic/azure/main.tf
examples/full/basic/gcp/main.tf
examples/full/private_endpoint/aws/aws.tf
examples/full/private_endpoint/aws/main.tf

towards: https://clickhouse-inc.slack.com/archives/C03S8DZN4MB/p1726712158265969
Use a random region for e2e tests to minimize throttling issues on a regional level

use a random region for e2e tests

---

examples/full/basic/aws/main.tf
examples/full/basic/gcp/main.tf

fix default region in examples

---

pkg/resource/service.go

Use terraform validators instead of custom ones where possible

Improve validation

---

docs/resources/service.md
examples/full/basic/aws/main.tf
examples/full/private_endpoint/aws/main.tf
pkg/internal/api/backup_configuration.go
pkg/internal/api/client_mock.go
pkg/internal/api/interface.go
pkg/internal/api/models.go
pkg/internal/api/service.go
pkg/resource/models/service_resource.go
pkg/resource/models/service_resource_test.go
pkg/resource/service.go
pkg/resource/service_test.go

Towards: https://github.com/ClickHouse/sre/issues/101
Add support for setting backupConfiguration options

Backup config

---

docs/resources/service.md
pkg/resource/service.go

Update `num_replicas` value on service only when `num_replicas` is not null and a known value.
Addresses #184

Update num_replicas when value is known

---

.github/actions/import/action.yaml
.github/workflows/import.yaml
.github/workflows/release.yaml
.gitignore
examples/full/development/aws/main.tf
examples/full/development/gcp/main.tf
examples/full/production/aws/main.tf
examples/full/production/gcp/main.tf
pkg/internal/api/models.go
pkg/resource/service.go
tests/import/service/main.tf
tests/import/service/provider.tf
tests/import/service/provider.tf.template

Towards: https://github.com/ClickHouse/sre/issues/120
add a new test that imports a clickhouse service into terraform

Test import

---

.github/actions/cleanup-clickhouse/action.yaml
.github/actions/e2e/action.yaml
.github/actions/import/action.yaml
.github/scripts/set_api_env.sh
.github/workflows/e2e.yaml
.github/workflows/import.yaml
.github/workflows/release.yaml

towards: https://github.com/ClickHouse/sre/issues/147
Allow running e2e and import on dev and staging envs + on a custom env

Allow testing custom env

---

.github/workflows/release.yaml

release CI created services with duplicate name, this PR fixes that

fix release CI duplicate name issue

---

examples/full/basic/aws/main.tf
examples/full/basic/azure/main.tf
examples/full/basic/gcp/main.tf

some examples needed to be aligned

fix examples

---

examples/rbac/main.tf
pkg/internal/api/client_mock.go
pkg/internal/api/db_grant_role.go
pkg/internal/api/interface.go
pkg/resource/descriptions/grant_role.md
pkg/resource/grant_role.go
pkg/resource/models/grant_role.go
pkg/resource/register_debug.go

Towards: https://github.com/ClickHouse/sre/issues/307
allow granting a "role" to either a "user" or to another "role".

add role grant resource

---

examples/full/basic/azure/main.tf
pkg/internal/api/common.go
pkg/resource/grant_privilege.go
pkg/resource/service.go

choice of releaseChannel only worked during an update.
Fixed to work on creation as well

Fix chosing of releaseChannel during service creation

---

pkg/internal/api/common.go

Fix field setting for debug log feature

---

examples/rbac/main.tf
pkg/internal/api/client_mock.go
pkg/internal/api/common.go
pkg/internal/api/db_grant_privilege.go
pkg/internal/api/db_grant_privilege_test.go
pkg/internal/api/interface.go
pkg/resource/grant_privilege.go

Try to mitigate ongoing issues with grant_privileges by making stricter validations.
Also allow granting global privileges.

Improve validation grant_privileges

---

pkg/resource/descriptions/grant_privilege.md
pkg/resource/grant_privilege.go

towards: https://github.com/ClickHouse/sre/issues/386
prevent using literal "*" as table name as it is confusing and does not do what it seems it does

Avoid wildcard table

---

examples/full/basic/azure/main.tf
pkg/internal/api/service.go
pkg/resource/service.go

Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/305 and https://github.com/ClickHouse/terraform-provider-clickhouse/issues/308

Avoid showing fields as "known after apply" if not needed.

---

examples/full/basic/aws/main.tf
pkg/resource/service.go

Towards: https://github.com/ClickHouse/terraform-provider-clickhouse/issues/305

Add UseStateForUnknown to all optional/computed fields

---

pkg/resource/service.go

Towards: https://github.com/ClickHouse/sre/issues/473
In order to make CMEK to TDE support work for terraform customers, we need to make changes on how we deal with a few fields.
This PR does just that.

Changes needed to support CMEK to TDE migration

---

development/README.md

Added a debugging section to the dev documentation.

Add debugging section to development documentation

---

.github/actions/e2e/action.yaml
.github/workflows/e2e.yaml
.github/workflows/release.yaml

fix(ci): e2e/release workflows
Example of tested e2e pipelines from feature branch with update=`true`:
https://github.com/ClickHouse/terraform-provider-clickhouse/actions/runs/16999166122
https://github.com/ClickHouse/terraform-provider-clickhouse/actions/runs/16998766395

fix(ci): e2e/release workflows

---

.github/workflows/comments.yaml

- Allow starting test from the PR with a comment
- Cannot test from PR -> https://github.com/orgs/community/discussions/59389

ci(test): add workflow to trigger tests with comment

---

.github/workflows/comments.yaml

- When there is nothing to process don't react to the comment

ci(comment): only react for valid comments
